### ISSUE TITLE
Random CORS errors in production - Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by lcnvdl** [FoalTS/foal#1015] opened 2021-12-15 23:47 UTC
Version of FoalTS: 2.5

Hi! I've deployed my FoalTS app in Azure as an Azure WebApp.

In development the app works fine, but I'm having some RANDOM issues in the production environment.

Error example:
``` 
Access to XMLHttpRequest at 'https://fg-api.azurewebsites.net/project/tales' from origin 'https://forja-games-api.web.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Sometimes, the request fails because the header Access-Control-Allow-Origin is missing. However, in my code, I've enabled that header in the global controller (appcontroller).

Check my app controller file:
```typescript
import { Context, controller, dependency, HttpResponse, IAppController, Store, UseSessions, HttpResponseInternalServerError, Options, HttpResponseNoContent, Hook } from '@foal/core';
import { fetchUser } from '@foal/typeorm';
import { createConnection } from 'typeorm';
import { User } from './entities';
import { ApiController, AuthController, CredentialController, ProjectController, UserController, WalletController } from './controllers';

@Hook(ctx => response => {
  response.setHeader('Access-Control-Allow-Origin', ctx.request.get('Origin') || '*');
  response.setHeader('Access-Control-Allow-Credentials', 'true');
})
@UseSessions({
  cookie: true,
  user: fetchUser(User)
})
export class AppController implements IAppController {
  // This line is required.
  @dependency
  store: Store;

  subControllers = [
    controller('/auth', AuthController),
    controller('/api', ApiController),
    controller('/project', ProjectController),
    controller('/credential', CredentialController),
    controller('/user', UserController),
    controller('/wallet', WalletController),
  ];

  async init() {
    await createConnection();
  }

  @Options('*')
  options(ctx: Context) {
    const response = new HttpResponseNoContent();
    response.setHeader('Access-Control-Allow-Methods', 'HEAD, GET, POST, PUT, PATCH, DELETE');
    response.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    return response;
  }

  handleError(error: Error, ctx: Context): HttpResponse | Promise<HttpResponse> {
    const customError = error as any;

    const errorJson = {
      message: customError.response?.data?.message || customError.response?.data?.description || error.message,
      path: ctx.request.path,
    };

    const response = new HttpResponseInternalServerError(errorJson);
    if (customError.response) {
      response.statusCode = customError.response.status;
      response.statusMessage = customError.response.statusText
    }

    console.error(errorJson);

    return response;
  }
}
```

Also, I'm attaching you two files.

1) The request working fine, status code 200.
2) The same request, exactly equals (a few seconds later), failing.

![Clipboard image 7](https://user-images.githubusercontent.com/5065981/146282413-1c7a3e7f-fb2c-4277-a7cd-1652b0245df6.png)
![Clipboard image 8](https://user-images.githubusercontent.com/5065981/146282416-48b9a6c1-db3e-4346-b154-f1c80c9c7647.png)

Do you have any idea or solution?

Thanks in advance.

Lucho.

**Comment by kingdun3284** [comment] 2021-12-16 04:26
@lcnvdl Just put these code out of this controller. So It can return the options before hitting the useSessions hook.
```
@Options('*')
  options(ctx: Context) {
    const response = new HttpResponseNoContent();
    response.setHeader('Access-Control-Allow-Methods', 'HEAD, GET, POST, PUT, PATCH, DELETE');
    response.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    return response;
  } 
```

**Comment by lcnvdl** [comment] 2021-12-16 13:06
> @lcnvdl Just put these code out of this controller. So It can always return the options before hitting the useSessions hook.
> 
> ```
> @Options('*')
>   options(ctx: Context) {
>     const response = new HttpResponseNoContent();
>     response.setHeader('Access-Control-Allow-Methods', 'HEAD, GET, POST, PUT, PATCH, DELETE');
>     response.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
>     return response;
>   } 
> ```

Hi kingdun3284. Thanks for your answer. I don't catch what you mean when you say "out of this controller". Where should be be the code?

**Comment by kingdun3284** [comment] 2021-12-16 16:05
```

export class AppParentController implements IAppController {
 
  subControllers = [
    controller('/', AppController)
  ];

  @Options('*')
  options(ctx: Context) {
    const response = new HttpResponseNoContent();
    response.setHeader('Access-Control-Allow-Methods', 'HEAD, GET, POST, PUT, PATCH, DELETE');
    response.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    return response;
  }

}
```
@lcnvdl , You need something like this to wrap your app controller. When browser request a cross-origin resource ,it will send a preflight request to the server, yet the preflight request can't pass the `@UseSession()` hook, sinece it doesn't contain the authorization header. Thus, you should move the `@Options` hook out of the contoller, or put `@UseSession()` inside of each of your sub-controller. This is not a bug anyway, so we can close it.

**Closed by kingdun3284** 2021-12-16 16:05 UTC
Labels: bug

**Comment by lcnvdl** [comment] 2021-12-16 17:07
Thanks, I'll try this. I didn't know that all the controllers could use the property subControllers, and not only the main one.
