### ISSUE TITLE
npm build:xxx scripts do not clean directories before compiling ts to js

### ISSUE THREAD

**Issue by opensas** [FoalTS/foal#626] opened 2020-02-06 20:30 UTC
When I delete a migration or entity or script and rebuild it, the previously compiled js files is still in the build folder.

Example, from the startup project, if I delete the file src/app/entities/user.entity.js and the run

```
$ npm run build:app
```

The files `build/app/entities/user.entity.js` and `build/app/entities/user.entity.js.map` remain in the build folder.

Or is there a better way to remove them than just deleting the ts file?

Same think happens with scripts and migration. And I guess that in the case of migrations this thing is even more dangerous, given that the remaining `build/migrations/xxx.js` files will still be executed even though the corresponding ts files no longer exist. Am I right?

Suggested solution:

Clear corresponding build folder before building app, test, e2e, scripts, migrations. If you agree with this approach I might give it a try and send you a PR

**Comment by LoicPoullain** [comment] 2020-02-07 11:21
Duplicate of #607

**Comment by LoicPoullain** [comment] 2020-02-07 11:24
Thank you for submitting this issue @opensas 

It is true it is annoying. A fix is on its way: #621. It will be released with version 1.6 this month 👍 

I'm closing the issue. Feel free to re-open it if needed

**Closed by LoicPoullain** 2020-02-07 11:24 UTC
Labels: duplicate, feature request

**Comment by opensas** [comment] 2020-02-07 12:30
I had a look at the open issues but #607 was already closed.

Thanks a lot for your effort and prompt reply. FoalTS looks pretty impressive, and I'm afraid I will keep bothering you with more issues and feature request ;-)
